import { COLORS } from '../tokens';

export const RED_THEME = {
    BASE: [COLORS.FANTASY[1]],
    CARD: [COLORS.SNOW[1]],
    BORDER: [COLORS.SNOW[1]],
    TITLE: [COLORS.NIGHT[1]],
    P: [COLORS.NIGHT[1]],
    LABEL: [COLORS.NIGHT[1]],
    CAPTION: [COLORS.GRAVEL[1]],
    ACTIVECAPTION: [COLORS.STORM[1]],
    DATE: [COLORS.GRAVEL[1]],
    ...COLORS,
};

export const DARK_THEME = {
    BASE: [COLORS.NIGHT[1]],
    CARD: [COLORS.NIGHT[1]],
    BORDER: [COLORS.OUTER_SPACE[1]],
    TITLE: [COLORS.SNOW[1]],
    P: [COLORS.SNOW[1]],
    LABEL: [COLORS.SNOW[1]],
    CAPTION: [COLORS.GRAVEL[1]],
    ACTIVECAPTION: [COLORS.STORM[1]],
    DATE: [COLORS.GRAVEL[1]],
    ...COLORS,
};
